name: recall
description: A simple flashcards app that can be beneficial for students who want to memorize some definitions
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:

  flex_color_scheme: ^7.3.1
  bloc: ^8.1.4
  cool_dropdown: ^2.1.0
  switcher_button: ^0.0.4
  get_storage: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  quickalert: ^1.1.0
  hive_flutter: ^1.1.0
  flutter_flip_card: ^0.0.6
dev_dependencies:
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/areYouSure.webp